### ISSUE TITLE
[SCRUM] Week of March 6th

### ISSUE THREAD

**Issue by yeskunall** [yeskunall/pproval.app#10]
Provides a platform for each team member to add comments with their own contributions.

Questions to be answered:

1. What have I done this week?
2. What will I do next week?
3. What is holding me back? (if applicable)

__NOTE__: Must be done before the end date

**Comment by PragyaJollySingh** [comment]
1. I did the model, creating the articles , the two repositories one for the possible users and one for the possible articles. Defined the the types of users that would interact with the system. 
2. We will be discussing this after the meeting today  
3. Conflicting of merging merging models, Java version between environment.

**Comment by ryanribeiro** [comment]
1. Managed the conflicts of merging the model into our repository, added a controller for the landing page, added some basic html pages that make use of bootstrap.
2. TBD
3. Issues with conflicting Java versions between environments.
