### ISSUE TITLE
[FEAT] The editor should be able to see all submitted articles

### ISSUE THREAD

**Issue by yeskunall** [yeskunall/pproval.app#17]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Acceptance criteria**

**Additional context**

**Comment by PragyaJollySingh** [comment]
Feature Prob: Looks at when an editor wants to view all articles and their status that are in the repository
Solution: Articles are in a repository and then can be viewed in the view in a chart format that presents key relevant information to the editor.
Acceptance Criteria: If one can view all the articles that are in the repository

**Comment by yeskunall** [comment]
This isn’t done yet. Reopening.
