### ISSUE TITLE
[FEAT] The editor should be able to approve/reject the article

### ISSUE THREAD

**Issue by yeskunall** [yeskunall/pproval.app#18]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Acceptance criteria**

**Additional context**

**Comment by PragyaJollySingh** [comment]
feature relation: The editor is able to accept and or reject any articles that are in review after which their status is then updated in the main view. 
Solution:
 #1 Checks to see if an article is under review 
# 2 then you can accept or reject the article even if it has no reviews attached 
#3 The status then updates on the view that shows all the articles 
Acceptance Criteria: You can rejects or accept an article but not both and then their status updates appropriately
