### ISSUE TITLE
[SCRUM] Week of March 20th

### ISSUE THREAD

**Issue by PragyaJollySingh** [yeskunall/pproval.app#23]
Provides a platform for each team member to add comments with their own contributions.

Questions to be answered:

1. What have I done this week?
Made the editors side of the web application 
An editor can accept/ reject an article 
An editor can view all articles 
Landing page for selecting which reviewers can be selected to review an article 
UML Diagrams for my end 
Write test cases for articles and submitters so that the functionalities can be tested

2. What will I do next week?
This will be determined after our regular meetings 

3. What is holding me back? (if applicable)
Drop down that can be populated with a for each loop 

__NOTE__: Must be done before the end date

**Comment by ryanribeiro** [comment]
1. What have I done this week?
- Partly implemented views for submitter
- Submitter can now view submitted articles
- Code reviews for PRs / testing the PRs
- Generated UML Diagrams using Intellij

2. What will I do next week?
- TBD based on group meeting, however I still personally have to finish the issues I had been assigned regarding submitter

3. What is holding me back?
- Mostly just a personal struggle of not understanding enough to do what I want

**Comment by yeskunall** [comment]
1. What have I done this week?

- Set up PostgreSQL on Heroku as well as locally
- Add support for authentication using Spring Security*

2. What will I do next week?

> TBD

3. What is holding me back?

- Tight schedule, and 3 concurrent projects right up until last week. Things should settle down now, and I should be able to dedicate a lot more time to this


__NOTE__: I was absent during today’s demo. @MikeVezina (sorry for the ping) I have updated this week’s SCRUM issue, so please take a look. Thank you.

\* PR landing soon enough. I will pin the PR here once I do.
